name: Notify with JS

on:
  push:
    branches:
      - main

jobs:
  run-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run JavaScript script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_WEBHOOKP: ${{ secrets.DISCORD_WEBHOOKP }}
        run: node notify.js
